services:
  app:
    build: .
    container_name: whatsia
    restart: unless-stopped
    volumes:
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./.wwebjs_cache:/usr/src/app/.wwebjs_cache
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - whatsia-network

networks:
  whatsia-network:
    driver: bridge